name: Pipeline Lab DevSecOps

on:
  push:
    branches: ["lab"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk-sast:
    name: Static Application Security Testing con Snyk
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SAST Snyk Code
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=medium
  snyk-sca:
    name: Software Composition Analysis con Snyk
    needs: snyk-sast
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SCA Snyk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=medium
  docker-build:
    name: Build Docker Image
    needs: snyk-sca
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build -t reddit-clone:latest .
  snyk-imagescan:
    name: Image Security con Snyk
    needs: docker-build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SCA Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: container test reddit-clone:latest
          args: --severity-threshold=medium