name: Pipeline Lab DevSecOps

on:
  push:
    branches: ["lab"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk-sast:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SAST Snyk Code
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: snyk code test
          args: --severity-threshold=medium --sarif-file-output=snyk.sarif
      
      - name: Subir resultados a GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif