name: Pipeline Lab DevSecOps

on:
  push:
    branches: ["lab"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk-sast:
    name: Static Application Security Testing con Snyk
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SAST Snyk Code
        uses: snyk/actions/node@master
        continue-on-error: true # Asegurarse que continue a SCA
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=medium
  snyk-sca:
    name: Software Composition Analysis con Snyk
    needs: snyk-sast
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SCA Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=medium